### ISSUE TITLE
fmLib

### ISSUE THREAD

**Issue by MazeBjornssom** [meesvrh/fmLib#6]
Good evening,
 I’m reaching out regarding the fmLib script because unfortunately, I’ve been struggling for four days to get my hunting script to work, but nothing seems to be working. I always encounter an error related to fmLib. Would it be possible to get some assistance so I can resolve this issue quickly?

**Comment by meesvrh** [comment]
Hi, support for scripts (hunting) are given by the creator (in this case, RX, we, are). For support, please enter RX Scripts discord and create a ticket.
